service: SLSWORDLCHECKWORD
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  checkword:
    handler: handler.checkword
    events:
      - httpApi:
          path: /date/{date}/length/{length}/word/{word}
          method: get
